### ISSUE TITLE
bundle.js encountered a panic. I followed the instructions as diligently as I can yet this happens and the website would not display

### ISSUE THREAD

**Issue by Qark-dev** [fkohlgrueber/yew-pwa-minimal#1]
Error with Permissions-Policy header: Unrecognized feature: 'interest-cohort'.
bundle.js:48 Encountered a panic!
__cargo_web_snippet_dc2fd915bd92f9e9c6a3bd15174f1414eee3dbaf @ bundle.js:48
imports.wbg.__wbg_cargowebsnippetdc2fd915bd92f9e9c6a3bd15174f1414eee3dbaf_ce5c721cab10d020 @ bundle.js:220
$func87 @ yew_wasm_pack_minimal_bg.wasm:0xadf7
$func88 @ yew_wasm_pack_minimal_bg.wasm:0xaf90
$func113 @ yew_wasm_pack_minimal_bg.wasm:0xc0f3
$func155 @ yew_wasm_pack_minimal_bg.wasm:0xcfa0
$func162 @ yew_wasm_pack_minimal_bg.wasm:0xd0ff
$func146 @ yew_wasm_pack_minimal_bg.wasm:0xcd16
$run_app @ yew_wasm_pack_minimal_bg.wasm:0xc9af
run_app @ bundle.js:143
main @ bundle.js:267
await in main (async)
(anonymous) @ bundle.js:269
(anonymous) @ bundle.js:271
bundle.js:44 Panic location: /home/qat/.cargo/registry/src/github.com-1ecc6299db9ec823/stdweb-0.4.20/src/webcore/serialization.rs:447
__cargo_web_snippet_72fc447820458c720c68d0d8e078ede631edd723 @ bundle.js:44
imports.wbg.__wbg_cargowebsnippet72fc447820458c720c68d0d8e078ede631edd723_ece3da0a4474dbeb @ bundle.js:226
$func87 @ yew_wasm_pack_minimal_bg.wasm:0xae9e
$func88 @ yew_wasm_pack_minimal_bg.wasm:0xaf90
$func113 @ yew_wasm_pack_minimal_bg.wasm:0xc0f3
$func155 @ yew_wasm_pack_minimal_bg.wasm:0xcfa0
$func162 @ yew_wasm_pack_minimal_bg.wasm:0xd0ff
$func146 @ yew_wasm_pack_minimal_bg.wasm:0xcd16
$run_app @ yew_wasm_pack_minimal_bg.wasm:0xc9af
run_app @ bundle.js:143
main @ bundle.js:267
await in main (async)
(anonymous) @ bundle.js:269
(anonymous) @ bundle.js:271
yew_wasm_pack_minimal_bg.wasm:0xafc6 Uncaught (in promise) RuntimeError: unreachable
    at yew_wasm_pack_minimal_bg.wasm:0xafc6
    at yew_wasm_pack_minimal_bg.wasm:0xc0f3
    at yew_wasm_pack_minimal_bg.wasm:0xcfa0
    at yew_wasm_pack_minimal_bg.wasm:0xd0ff
    at yew_wasm_pack_minimal_bg.wasm:0xcd16
    at yew_wasm_pack_minimal_bg.wasm:0xc9af
    at run_app (bundle.js:143:18)
    at main (bundle.js:267:8)

**Comment by fkohlgrueber** [comment]
Hi, thanks for raising the issue. It's quite possible that this project doesn't build anymore. Rust / wasm / yew is moving fast and I haven't updated the project in a long time. 

I'm quite busy currently, but I'll try to take a look at the issue within the next two weeks. Feel free to remind me again if you don't hear from me within that time frame.

**Comment by fkohlgrueber** [comment]
I don't know what exactly is going wrong in your setup, the project still seemed to work fine for me.

Anyway, since the project was quite outdated, I thought it would be good to do an update. I've updated yew to the latest version (0.19) and changed the bundler from wasm-pack to trunk. That's the tool yew recommends currently and in my experience, it works pretty well. 

Can you try again with the current master? Let me know if you still encounter issues.

**Comment by jpearnshaw** [comment]
Project works fine for me after the upgrade to trunk. It was a helpful head start .. thanks.

Only one thing: lines 5 & 6 of the service worker need removing, a hangover from wasm-pack I think. They cause an error to be thrown. Noticed when the project failed Lighthouse. 
 
```
  './pkg/bundle.js',
  './pkg/yew_wasm_pack_minimal_bg.wasm'
```

**Comment by fkohlgrueber** [comment]
@jpearnshaw Thanks for pointing that out, seems like I missed it. I don't think though that simply removing the files from the list is the way to go. AFAIK, the caching in the service worker is needed for the app to work offline too. If two files aren't cached, the app probably won't load when you're offline. I created #3 to track that issue.

@Qark-dev I'll close this issue. Feel free to reopen if you're still having issues running the example
